/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Insight {
  'id' : bigint,
  'title' : string,
  'implications' : string,
  'summary' : string,
}
export interface RangeScenario {
  'id' : bigint,
  'rangeEstimate' : string,
  'name' : string,
  'description' : string,
  'uncertaintyBand' : string,
}
export interface SolutionFeature {
  'id' : bigint,
  'estimatedImpact' : string,
  'name' : string,
  'description' : string,
}
export interface _SERVICE {
  'getInsights' : ActorMethod<[], Array<Insight>>,
  'getInteractionStats' : ActorMethod<
    [],
    {
      'scenarioBreakdown' : Array<[bigint, bigint]>,
      'screenBreakdown' : Array<[string, bigint]>,
      'totalInteractions' : bigint,
    }
  >,
  'getRangeScenarios' : ActorMethod<[], Array<RangeScenario>>,
  'getSolutionFeatures' : ActorMethod<[], Array<SolutionFeature>>,
  'initializeRangeData' : ActorMethod<[], undefined>,
  'recordInteraction' : ActorMethod<
    [bigint, [] | [bigint], string, string],
    undefined
  >,
  'resetDemoData' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];