/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Insight = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'implications' : IDL.Text,
  'summary' : IDL.Text,
});
export const RangeScenario = IDL.Record({
  'id' : IDL.Nat,
  'rangeEstimate' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'uncertaintyBand' : IDL.Text,
});
export const SolutionFeature = IDL.Record({
  'id' : IDL.Nat,
  'estimatedImpact' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'getInsights' : IDL.Func([], [IDL.Vec(Insight)], ['query']),
  'getInteractionStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'scenarioBreakdown' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
          'screenBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'totalInteractions' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getRangeScenarios' : IDL.Func([], [IDL.Vec(RangeScenario)], ['query']),
  'getSolutionFeatures' : IDL.Func([], [IDL.Vec(SolutionFeature)], ['query']),
  'initializeRangeData' : IDL.Func([], [], []),
  'recordInteraction' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text],
      [],
      [],
    ),
  'resetDemoData' : IDL.Func([], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Insight = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'implications' : IDL.Text,
    'summary' : IDL.Text,
  });
  const RangeScenario = IDL.Record({
    'id' : IDL.Nat,
    'rangeEstimate' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'uncertaintyBand' : IDL.Text,
  });
  const SolutionFeature = IDL.Record({
    'id' : IDL.Nat,
    'estimatedImpact' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'getInsights' : IDL.Func([], [IDL.Vec(Insight)], ['query']),
    'getInteractionStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'scenarioBreakdown' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
            'screenBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'totalInteractions' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getRangeScenarios' : IDL.Func([], [IDL.Vec(RangeScenario)], ['query']),
    'getSolutionFeatures' : IDL.Func([], [IDL.Vec(SolutionFeature)], ['query']),
    'initializeRangeData' : IDL.Func([], [], []),
    'recordInteraction' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text],
        [],
        [],
      ),
    'resetDemoData' : IDL.Func([], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };